/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCLOCK_H
#define _MOCKCLOCK_H

#include "unity.h"
#include "clock.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockclock_Init(void);
void Mockclock_Destroy(void);
void Mockclock_Verify(void);




#define get_current_hour_Expect() TEST_FAIL_MESSAGE("get_current_hour requires _ExpectAndReturn");
#define get_current_hour_ExpectAndReturn(cmock_retval) get_current_hour_CMockExpectAndReturn(__LINE__, cmock_retval)
void get_current_hour_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
