/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockclock.h"

static const char* CMockString_get_current_hour = "get_current_hour";

typedef struct _CMOCK_get_current_hour_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;

} CMOCK_get_current_hour_CALL_INSTANCE;

static struct MockclockInstance
{
  CMOCK_MEM_INDEX_TYPE get_current_hour_CallInstance;
} Mock;


void Mockclock_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.get_current_hour_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_current_hour);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockclock_Init(void)
{
  Mockclock_Destroy();
}

void Mockclock_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int get_current_hour(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_current_hour_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_current_hour);
  cmock_call_instance = (CMOCK_get_current_hour_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_current_hour_CallInstance);
  Mock.get_current_hour_CallInstance = CMock_Guts_MemNext(Mock.get_current_hour_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void get_current_hour_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_current_hour_CALL_INSTANCE));
  CMOCK_get_current_hour_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_current_hour_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_current_hour_CallInstance = CMock_Guts_MemChain(Mock.get_current_hour_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

